name: protoc_plugin
version: 19.0.2
description: Protoc compiler plugin to generate Dart code
homepage: https://github.com/dart-lang/protobuf

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  fixnum: ^0.10.9
  path: ^1.0.0
  protobuf:
    git:
      url: https://github.com/factisresearch/protobuf.git
      ref: e716cd39bd38f80edb879868aebdcee3287f488f
      path: protobuf
  dart_style: ^1.0.6

dev_dependencies:
  test: ^1.3.0

executables:
  protoc-gen-dart: protoc_plugin
